### ISSUE TITLE
MemoryError on a high dimensional dataset ~50k examples ~30k dimensions

### ISSUE THREAD

**Issue by pbamotra** [Jianbo-Lab/CCM#1]
Platform: Ubuntu 14.04
Setup: AWS p2.xlarge (61 GiB RAM)

```
MemoryError                               Traceback (most recent call last)
<ipython-input-53-12bcb75ecca9> in <module>()
----> 1 rank = ccm.ccm(features, labels, 1000, 'categorical', 0.001, iterations = 100, verbose = True)

/core/ccm.py in ccm(X, Y, num_features, type_Y, epsilon, learning_rate, iterations, verbose)
    205         transform_Y = 'one-hot'
    206 
--> 207     fs = CCM(X, Y, transform_Y, epsilon)
    208     w = fs.solve_gradient_descent(num_features, learning_rate, iterations, verbose)
    209     if verbose:

/core/ccm.py in __init__(self, X, Y, transform_Y, epsilon)
     90 
     91         # Use Gaussian kernel with automatically chosen sigma.
---> 92         sigma = np.median(np.linalg.norm(X[:, None, :] - X[None, :, :], axis=2))
     93         kernel_X = kernel.GaussianKernel(sigma)
     94 

MemoryError:

```

**Comment by Jianbo-Lab** [comment]
The error itself is caused by the memory requirement of storing 'X[:, None, :] - X[None, :, :]', which is n * n * d, and may be fixed by a more clever calculation of the pairwise distance, like a sequential calculation.
But since the memory requirements of our algorithm are quadratic in the number of examples, working with datasets this large will be difficult using our current implementation. Scalability for kernel-based feature selection methods is an important open problem that we hope to address in future work. 

Jianbo

**Comment by pbamotra** [comment]
Thank you.
